# Generated by Django 4.1.2 on 2022-10-09 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_cart_products_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prodcut_category',
            new_name='product_category',
        ),
    ]
